theme: minima
title: Awesome Geophysics
description: A community-curated, ever-evolving collection of resources that spans the full spectrum of geophysical sciences.
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
author:
  name: "Mahdi Farmahini Farahani"
  github: "https://github.com/aradfarahani"
