name: Validate New Entries in Awesome Geophysics

on:
  push:
    paths:
      - "awesome_geophysics.json"
      - "scripts/validate_new_entries.py"
    branches: [main]
  
  pull_request:
    paths:
      - "awesome_geophysics.json"
      - "scripts/validate_new_entries.py"
    branches: [main]
  
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Run validation
        shell: bash
        run: |
          python scripts/validate_new_entries.py 2>&1 | while read line; do
            echo "::error::$line"
          done